"""add_food_tables

Revision ID: 1a12fe2b1f59
Revises:
Create Date: 2024-08-01 20:11:35.506709+03:00
"""
import sqlalchemy as sa
from alembic import op

revision = "1a12fe2b1f59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "food_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Наименование"),
        sa.Column("is_published", sa.Boolean(), nullable=False, comment="Признак заявленной категории"),
        sa.PrimaryKeyConstraint("id"),
        comment="Категория блюда",
    )
    op.create_table(
        "topping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Наименование"),
        sa.PrimaryKeyConstraint("id"),
        comment="Ингредиент",
    )
    op.create_table(
        "food",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False, comment="Описание"),
        sa.Column("price", sa.Integer(), nullable=False, comment="Цена"),
        sa.Column("is_special", sa.Boolean(), nullable=False, comment="Признак специального блюда"),
        sa.Column("is_vegan", sa.Boolean(), nullable=False, comment="Признак вегатерианского блюда"),
        sa.Column("is_published", sa.Boolean(), nullable=False, comment="Признак заявленного блюда"),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["food_category.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Блюдо",
    )
    op.create_table(
        "topping__food__reference",
        sa.Column("topping_id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food.id"],
        ),
        sa.ForeignKeyConstraint(["topping_id"], ["topping.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("topping_id", "food_id"),
        comment="\n    Таблица m2m для связи ингредиентов и блюд\n    ",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topping__food__reference")
    op.drop_table("food")
    op.drop_table("topping")
    op.drop_table("food_category")
    # ### end Alembic commands ###
