repos:
-   repo: local
    hooks:
    - id: flake8
      name: flake8
      entry: bash -c 'source .venv/bin/activate && flake8 app'
      language: python
      additional_dependencies: [ pre-commit, flake8 ]